server:
  port: 8088

spring:
  application:
    name: delivery-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}

delivery:
  store:
    name: "Blinkit Dark Store - Bangalore"
    address: "Koramangala, Bangalore, Karnataka 560034"
    lat: 12.9352
    lng: 77.6245
  cooldown-minutes: 5   # partner rest period after completing a delivery
